# Generated by Django 4.2.7 on 2026-02-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0002_add_goal_model'),
        ('litigation_management', '0006_add_missing_timestamp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcase',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigation_cases', to='contract_management.businesscontract', verbose_name='关联合同'),
        ),
    ]
