# Generated by Django 4.2.7 on 2025-12-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0002_administrativeaffair_affairprogressrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affairprogressrecord',
            name='affair',
        ),
        migrations.RemoveField(
            model_name='affairprogressrecord',
            name='recorder',
        ),
        migrations.RemoveField(
            model_name='affairstatushistory',
            name='affair',
        ),
        migrations.RemoveField(
            model_name='affairstatushistory',
            name='operator',
        ),
        migrations.RemoveIndex(
            model_name='officesupply',
            name='admin_offic_categor_384180_idx',
        ),
        migrations.RemoveField(
            model_name='officesupply',
            name='category',
        ),
        migrations.AddIndex(
            model_name='officesupply',
            index=models.Index(fields=['supply_category', 'is_active'], name='admin_offic_supply__42e153_idx'),
        ),
        migrations.DeleteModel(
            name='AffairProgressRecord',
        ),
        migrations.DeleteModel(
            name='AffairStatusHistory',
        ),
    ]
