# Generated by Django 4.2.7 on 2026-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0006_alter_sealusage_usage_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealborrowing',
            name='status',
            field=models.CharField(choices=[('pending_approval', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('borrowed', '借用中'), ('pending_return_confirmation', '待确认归还'), ('returned', '已归还'), ('overdue', '逾期')], default='pending_approval', max_length=30, verbose_name='状态'),
        ),
    ]
