# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative_management', '0007_fix_seal_borrowing_status_length'),
    ]

    operations = [
        # 此迁移用于记录添加新的状态选项 'pending_return_confirmation'（待确认归还）
        # 注意：STATUS_CHOICES 是 Python 级别的选择，不影响数据库结构
        # 此状态用于印章归还流程：借用人提交归还申请后，需要保管员确认才能完成归还
        # 数据库中的 status 字段（CharField）已经可以存储此值，无需修改数据库结构
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
