# Generated by Django 4.2.7 on 2026-01-30 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_management', '0012_rename_system_fee_status_8a3f2d_idx_system_feed_status_5259c5_idx_and_more'),
        ('administrative_management', '0008_add_pending_return_confirmation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=100, unique=True, verbose_name='申请单号')),
                ('application_date', models.DateField(default=django.utils.timezone.now, verbose_name='申请日期')),
                ('loan_type', models.CharField(choices=[('personal', '个人借款'), ('business', '业务借款'), ('emergency', '应急借款'), ('other', '其他')], default='business', max_length=20, verbose_name='借款类型')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='借款金额')),
                ('loan_reason', models.TextField(verbose_name='借款事由')),
                ('expected_repay_date', models.DateField(blank=True, null=True, verbose_name='预计还款日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('paid', '已放款'), ('repaid', '已还款'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_notes', models.TextField(blank=True, verbose_name='审批意见')),
                ('paid_time', models.DateTimeField(blank=True, null=True, verbose_name='放款时间')),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已还金额')),
                ('repaid_time', models.DateTimeField(blank=True, null=True, verbose_name='还款时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='system_management.department', verbose_name='申请部门')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_loans', to=settings.AUTH_USER_MODEL, verbose_name='放款人')),
            ],
            options={
                'verbose_name': '借款申请',
                'verbose_name_plural': '借款申请',
                'db_table': 'admin_loan_application',
                'ordering': ['-application_date', '-created_time'],
                'indexes': [models.Index(fields=['applicant', 'status'], name='admin_loan__applica_c0c2c7_idx'), models.Index(fields=['application_date', 'status'], name='admin_loan__applica_09a779_idx')],
            },
        ),
    ]
