# 商机管理 - 页面视图聚合
# 从子模块聚合导出，供 urls_pages 使用

from .views_opportunity import (
    opportunity_management_home,
    opportunity_management,
    opportunity_detail,
    opportunity_submit_for_approval,
    opportunity_create,
    opportunity_edit,
    opportunity_delete,
    opportunity_status_transition,
    opportunity_followup_create,
    opportunity_followup_edit,
    opportunity_followup_delete,
    opportunity_evaluation_application,
    opportunity_warehouse_application,
    opportunity_warehouse_list,
    opportunity_bid_bond_payment,
    opportunity_tender_fee_payment,
    opportunity_agency_fee_payment,
    opportunity_drawing_evaluation,
    opportunity_tech_meeting,
    opportunity_followup_list,
    opportunity_sales_forecast,
    opportunity_win_loss,
    opportunity_win_loss_select,
    opportunity_mark_win_loss,
    opportunity_business_negotiation,
    opportunity_business_negotiation_form,
)
from .views_bidding import (
    opportunity_bidding_quotation,
    opportunity_bidding_quotation_application,
    opportunity_bidding_document_preparation,
    opportunity_bidding_document_submission,
    bidding_quotation_create,
    bidding_quotation_detail,
    bidding_quotation_edit,
)
from .views_import import opportunity_import

__all__ = [
    'opportunity_management_home',
    'opportunity_management',
    'opportunity_detail',
    'opportunity_submit_for_approval',
    'opportunity_create',
    'opportunity_edit',
    'opportunity_delete',
    'opportunity_status_transition',
    'opportunity_followup_create',
    'opportunity_followup_edit',
    'opportunity_followup_delete',
    'opportunity_evaluation_application',
    'opportunity_warehouse_application',
    'opportunity_warehouse_list',
    'opportunity_bid_bond_payment',
    'opportunity_tender_fee_payment',
    'opportunity_agency_fee_payment',
    'opportunity_drawing_evaluation',
    'opportunity_bidding_quotation',
    'opportunity_bidding_quotation_application',
    'opportunity_bidding_document_preparation',
    'opportunity_bidding_document_submission',
    'bidding_quotation_create',
    'bidding_quotation_detail',
    'bidding_quotation_edit',
    'opportunity_tech_meeting',
    'opportunity_followup_list',
    'opportunity_sales_forecast',
    'opportunity_win_loss',
    'opportunity_win_loss_select',
    'opportunity_mark_win_loss',
    'opportunity_business_negotiation',
    'opportunity_business_negotiation_form',
    'opportunity_import',
]
