# Generated by Django 4.2.7 on 2026-01-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_management', '0001_initial'),
    ]

    operations = [
    ]
