# Generated by Django 4.2.7 on 2026-01-30 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_management', '0002_initial_migration'),
        ('customer_management', '0057_remove_biddingquotation_created_by_and_more'),
        ('production_management', '0041_remove_preoptimizationmaterial_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 添加缺失的外键列
        migrations.AddField(
            model_name='businessopportunity',
            name='client',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='opportunities',
                to='customer_management.client',
                verbose_name='关联客户',
                null=True,  # 临时允许null，以便迁移现有数据
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='business_manager',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='managed_opportunities',
                to=settings.AUTH_USER_MODEL,
                verbose_name='负责商务',
                null=True,  # 临时允许null，以便迁移现有数据
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='created_opportunities',
                to=settings.AUTH_USER_MODEL,
                verbose_name='创建人',
                null=True,  # 临时允许null，以便迁移现有数据
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='approver',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_opportunities',
                to=settings.AUTH_USER_MODEL,
                verbose_name='审批人'
            ),
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='service_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='opportunities',
                to='production_management.servicetype',
                verbose_name='服务类型'
            ),
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='drawing_stage',
            field=models.ForeignKey(
                blank=True,
                db_column='drawing_stage',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='opportunities',
                to='production_management.designstage',
                verbose_name='图纸阶段'
            ),
        ),
    ]
