# Generated by Django 4.2.7 on 2026-02-05 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0059_add_goal_model'),
        ('production_management', '0044_add_goal_model'),
        ('opportunity_management', '0007_add_opportunity_project_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessopportunity',
            name='business_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='负责商务'),
        ),
        migrations.AlterField(
            model_name='businessopportunity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='customer_management.client', verbose_name='关联客户'),
        ),
        migrations.AlterField(
            model_name='businessopportunity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='businessopportunity',
            name='project',
            field=models.ForeignKey(blank=True, help_text='B3 结构化锚点：商机关联的生产管理项目，便于合同/委托书选择商机时回填', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='production_management.project', verbose_name='关联项目'),
        ),
    ]
