# Generated by Django 4.2.7 on 2025-12-24 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0013_outgoingdocument_confirmed_at_and_more'),
        ('archive_management', '0003_filecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepushrecord',
            name='delivery_record',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_push_records', to='delivery_customer.deliveryrecord', verbose_name='交付记录'),
        ),
        migrations.AlterField(
            model_name='projectdeliveryarchive',
            name='delivery_record',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_archive_records', to='delivery_customer.deliveryrecord', verbose_name='交付记录'),
        ),
    ]
