# Generated by Django 4.2.7 on 2026-01-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0040_add_parse_progress_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteamnotification',
            name='category',
            field=models.CharField(choices=[('team_change', '团队变更'), ('quality_alert', '质量提醒'), ('approval', '审批通知'), ('approval_result', '审批结果')], default='team_change', max_length=50, verbose_name='通知分类'),
        ),
    ]
