# Generated by Django 4.2.7 on 2026-01-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_management', '0001_initial'),
        ('production_management', '0041_remove_preoptimizationmaterial_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontract',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='opportunity_management.businessopportunity', verbose_name='关联商机'),
        ),
    ]
