# Generated by Django 4.2.7 on 2026-01-07 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0041_alter_projectteamnotification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAutoTransferConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_task_type', models.CharField(choices=[('project_complete_info', '完善项目信息'), ('configure_team', '配置项目团队'), ('client_upload_pre_docs', '甲方上传优化前资料'), ('client_resubmit_pre_docs', '甲方补充/重传资料'), ('internal_precheck_docs', '我方预审优化前资料'), ('client_issue_start_notice', '甲方发布开工通知')], help_text='选择完成后需要触发转交的任务类型', max_length=64, verbose_name='源任务类型')),
                ('target_task_type', models.CharField(choices=[('project_complete_info', '完善项目信息'), ('configure_team', '配置项目团队'), ('client_upload_pre_docs', '甲方上传优化前资料'), ('client_resubmit_pre_docs', '甲方补充/重传资料'), ('internal_precheck_docs', '我方预审优化前资料'), ('client_issue_start_notice', '甲方发布开工通知')], help_text='源任务完成后自动创建的任务类型', max_length=64, verbose_name='目标任务类型')),
                ('condition_type', models.CharField(choices=[('always', '总是执行'), ('on_success', '仅成功时执行'), ('on_failure', '仅失败时执行')], default='always', help_text='选择何时触发自动转交', max_length=20, verbose_name='执行条件')),
                ('is_active', models.BooleanField(default=True, help_text='取消勾选可临时禁用此转交规则，无需删除配置', verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, help_text='数字越小越先执行，相同顺序按创建时间排序', verbose_name='执行顺序')),
                ('delay_hours', models.IntegerField(default=0, help_text='源任务完成后延迟多少小时再创建目标任务，0表示立即执行', verbose_name='延迟执行（小时）')),
                ('description', models.TextField(blank=True, help_text='描述此转交规则的业务场景和用途，便于后续维护', verbose_name='配置说明')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_transfer_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '任务自动转交配置',
                'verbose_name_plural': '任务自动转交配置',
                'db_table': 'production_task_auto_transfer_config',
                'ordering': ['source_task_type', 'order', 'created_time'],
                'indexes': [models.Index(fields=['source_task_type', 'is_active'], name='production__source__856c6d_idx'), models.Index(fields=['target_task_type'], name='production__target__612d44_idx'), models.Index(fields=['is_active', 'order'], name='production__is_acti_4588f5_idx')],
                'unique_together': {('source_task_type', 'target_task_type', 'condition_type')},
            },
        ),
    ]
