# Generated by Django 4.2.7 on 2026-01-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0042_add_task_auto_transfer_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='task_type',
            field=models.CharField(choices=[('project_complete_info', '完善项目信息'), ('configure_team', '配置项目团队'), ('client_upload_pre_docs', '甲方上传优化前资料'), ('client_resubmit_pre_docs', '甲方补充/重传资料'), ('internal_precheck_docs', '我方预审优化前资料'), ('client_issue_start_notice', '甲方发布开工通知'), ('internal_compile_opinions', '编制咨询意见'), ('internal_review_opinions', '完成内部审核'), ('push_report_to_client', '推送咨询意见书'), ('design_reply_opinions', '设计方回复咨询意见'), ('client_confirm_meeting', '甲方确认三方会议'), ('organize_tripartite_meeting', '组织三方会议'), ('design_upload_revisions', '设计方上传改图成果'), ('internal_verify_revisions', '我方核图确认'), ('client_confirm_outcome', '甲方确认优化成果')], max_length=64, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='taskautotransferconfig',
            name='source_task_type',
            field=models.CharField(choices=[('project_complete_info', '完善项目信息'), ('configure_team', '配置项目团队'), ('client_upload_pre_docs', '甲方上传优化前资料'), ('client_resubmit_pre_docs', '甲方补充/重传资料'), ('internal_precheck_docs', '我方预审优化前资料'), ('client_issue_start_notice', '甲方发布开工通知'), ('internal_compile_opinions', '编制咨询意见'), ('internal_review_opinions', '完成内部审核'), ('push_report_to_client', '推送咨询意见书'), ('design_reply_opinions', '设计方回复咨询意见'), ('client_confirm_meeting', '甲方确认三方会议'), ('organize_tripartite_meeting', '组织三方会议'), ('design_upload_revisions', '设计方上传改图成果'), ('internal_verify_revisions', '我方核图确认'), ('client_confirm_outcome', '甲方确认优化成果')], help_text='选择完成后需要触发转交的任务类型', max_length=64, verbose_name='源任务类型'),
        ),
        migrations.AlterField(
            model_name='taskautotransferconfig',
            name='target_task_type',
            field=models.CharField(choices=[('project_complete_info', '完善项目信息'), ('configure_team', '配置项目团队'), ('client_upload_pre_docs', '甲方上传优化前资料'), ('client_resubmit_pre_docs', '甲方补充/重传资料'), ('internal_precheck_docs', '我方预审优化前资料'), ('client_issue_start_notice', '甲方发布开工通知'), ('internal_compile_opinions', '编制咨询意见'), ('internal_review_opinions', '完成内部审核'), ('push_report_to_client', '推送咨询意见书'), ('design_reply_opinions', '设计方回复咨询意见'), ('client_confirm_meeting', '甲方确认三方会议'), ('organize_tripartite_meeting', '组织三方会议'), ('design_upload_revisions', '设计方上传改图成果'), ('internal_verify_revisions', '我方核图确认'), ('client_confirm_outcome', '甲方确认优化成果')], help_text='源任务完成后自动创建的任务类型', max_length=64, verbose_name='目标任务类型'),
        ),
    ]
