# Generated by Django 4.2.7 on 2026-02-05 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0043_remove_base_data_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='目标名称')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('terminated', '已终止')], default='not_started', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_created_goals', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_owned_goals', to=settings.AUTH_USER_MODEL, verbose_name='归属人')),
            ],
            options={
                'verbose_name': '目标',
                'verbose_name_plural': '目标',
                'db_table': 'production_management_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['owner', 'status'], name='production__owner_i_8422a4_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['created_by'], name='production__created_643a6e_idx'),
        ),
    ]
