# Generated by Django 4.2.7 on 2026-01-08 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('production_management', '0043_update_task_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='org.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='businesscontract',
            name='org_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='org.department', verbose_name='所属部门'),
        ),
    ]
