# Generated by Django 4.2.7 on 2026-02-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_management', '0006_alter_contractsettlement_table_and_more'),
        ('production_management', '0044_add_goal_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscontract',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='business_manager',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='client',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='department',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='parent_contract',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='project',
        ),
        migrations.RemoveField(
            model_name='businesscontract',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='businesspaymentplan',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractparty',
            name='contract',
        ),
        migrations.DeleteModel(
            name='ResultFileType',
        ),
        migrations.DeleteModel(
            name='ComprehensiveAdjustmentCoefficient',
        ),
        migrations.DeleteModel(
            name='BusinessContract',
        ),
        migrations.DeleteModel(
            name='BusinessPaymentPlan',
        ),
        migrations.DeleteModel(
            name='ContractParty',
        ),
    ]
