# Generated by Django 4.2.7 on 2026-01-08 01:20

from django.db import migrations


def backfill_contract_org(apps, schema_editor):
    """从 client 回填合同的 company/department"""
    BusinessContract = apps.get_model("production_management", "BusinessContract")

    # 仅回填空值
    qs = BusinessContract.objects.select_related("client").filter(company__isnull=True)
    for c in qs.iterator():
        client = getattr(c, "client", None)
        if client and getattr(client, "company_id", None):
            c.company_id = client.company_id
        if client and getattr(client, "department_id", None):
            c.org_department_id = client.department_id
        c.save(update_fields=["company", "org_department"])


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0044_businesscontract_company_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_contract_org, migrations.RunPython.noop),
    ]
