# Generated by Django 4.2.7 on 2026-01-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0014_todotask_completion_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksummary',
            name='summary_content',
            field=models.TextField(blank=True, help_text='使用DeepSeek语言模型生成的简报内容', verbose_name='AI生成的简报内容'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('in_progress', '执行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('paused', '已暂停'), ('delayed', '已延期')], default='draft', max_length=20, verbose_name='计划状态'),
        ),
    ]
