# Generated by Django 4.2.7 on 2026-01-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0015_add_summary_content_to_work_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicgoal',
            name='value_choices',
            field=models.JSONField(blank=True, default=list, help_text='选择型指标的选项列表，格式：[{"value": "1", "label": "选项1"}, ...]', verbose_name='选择项'),
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='indicator_type',
            field=models.CharField(choices=[('numeric', '数值型'), ('percentage', '百分比型'), ('boolean', '布尔型'), ('text', '文本型'), ('choice', '选择型')], max_length=20, verbose_name='指标类型'),
        ),
    ]
