# Generated by Django 4.2.7 on 2026-02-06 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan_management', '0017_plan_company_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneEvidenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_code', models.CharField(db_index=True, max_length=100, verbose_name='产值里程碑编码')),
                ('required_event_types', models.JSONField(default=list, help_text='如 ["consult_submit", "review_done"]', verbose_name='所需事件类型列表')),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, help_text='可选，如完成度百分比阈值', max_digits=5, null=True, verbose_name='阈值（可选）')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '里程碑证据规则',
                'verbose_name_plural': '里程碑证据规则',
                'db_table': 'plan_milestone_evidence_rule',
            },
        ),
        migrations.AlterField(
            model_name='strategicgoal',
            name='indicator_type',
            field=models.CharField(choices=[('numeric', '数值型'), ('percentage', '百分比型'), ('text', '文本型')], max_length=20, verbose_name='指标类型'),
        ),
        migrations.CreateModel(
            name='PlanOutputMilestoneCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.PositiveIntegerField(db_index=True, verbose_name='商机ID')),
                ('milestone_code', models.CharField(db_index=True, max_length=100, verbose_name='产值里程碑编码')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='完成时间')),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict, verbose_name='证据快照')),
            ],
            options={
                'verbose_name': '产值里程碑完成记录',
                'verbose_name_plural': '产值里程碑完成记录',
                'db_table': 'plan_output_milestone_completion',
                'indexes': [models.Index(fields=['opportunity_id', 'milestone_code'], name='plan_output_opportu_9b9650_idx')],
                'unique_together': {('opportunity_id', 'milestone_code')},
            },
        ),
        migrations.CreateModel(
            name='FactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='事件类型')),
                ('ref_model', models.CharField(blank=True, max_length=100, verbose_name='关联模型')),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='关联ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发生时间')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('source_app', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='来源应用')),
            ],
            options={
                'verbose_name': '证据事件',
                'verbose_name_plural': '证据事件',
                'db_table': 'plan_fact_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['type', '-occurred_at'], name='plan_fact_e_type_08d59c_idx')],
            },
        ),
    ]
