# Generated by Django 4.2.7 on 2025-12-30 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_management', '0002_rename_api_call_lo_api_int_pqr678_idx_api_call_lo_api_int_5f3522_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiIpWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='需要添加到白名单的IP地址（IPv4或IPv6）', verbose_name='IP地址')),
                ('description', models.CharField(blank=True, help_text='说明此IP的用途，如：开发服务器、生产服务器等', max_length=200, verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ip_whitelists', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('external_system', models.ForeignKey(help_text='选择需要配置IP白名单的外部系统（如启信宝）', on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelists', to='api_management.externalsystem', verbose_name='所属系统')),
            ],
            options={
                'verbose_name': 'API IP白名单',
                'verbose_name_plural': 'API IP白名单',
                'db_table': 'api_ip_whitelist',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['external_system', 'status'], name='api_ip_whit_externa_5fc06d_idx'), models.Index(fields=['ip_address', 'is_active'], name='api_ip_whit_ip_addr_65ff1e_idx'), models.Index(fields=['created_time'], name='api_ip_whit_created_57b2c9_idx')],
                'unique_together': {('external_system', 'ip_address')},
            },
        ),
    ]
