# Generated by Django 4.2.7 on 2025-12-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_management', '0004_remove_settlementitem_settlement__opinion_ef0b16_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='settlementitem',
            name='settlement__opinion_ef0b16_idx',
        ),
    ]
