# Generated by Django 4.2.7 on 2026-02-05 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_management', '0004_remove_settlementitem_settlement__opinion_ef0b16_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeeJumpPointRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='当节省金额超过此阈值时，全部节省金额适用该系数', max_digits=14, verbose_name='跳点阈值')),
                ('rate', models.DecimalField(decimal_places=2, help_text='该阈值对应的取费系数，例如：15.0 表示 15%', max_digits=5, verbose_name='取费系数(%)')),
                ('description', models.TextField(blank=True, verbose_name='跳点说明')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '跳点提成配置',
                'verbose_name_plural': '跳点提成配置',
                'db_table': 'settlement_service_fee_jump_point_rate',
                'ordering': ['scheme', 'order', 'threshold'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceFeeSegmentedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='该分段的上限阈值，例如：500000 表示50万元', max_digits=14, verbose_name='分段阈值')),
                ('rate', models.DecimalField(decimal_places=2, help_text='该分段对应的取费系数，例如：10.5 表示 10.5%', max_digits=5, verbose_name='取费系数(%)')),
                ('description', models.TextField(blank=True, verbose_name='分段说明')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分段递增提成配置',
                'verbose_name_plural': '分段递增提成配置',
                'db_table': 'settlement_service_fee_segmented_rate',
                'ordering': ['scheme', 'order', 'threshold'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceFeeSettlementScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='结算方案的名称', max_length=200, verbose_name='方案名称')),
                ('code', models.CharField(blank=True, help_text='可选，用于系统识别', max_length=50, null=True, unique=True, verbose_name='方案代码')),
                ('description', models.TextField(blank=True, verbose_name='方案描述')),
                ('settlement_method', models.CharField(choices=[('fixed_total', '固定总价'), ('fixed_unit', '固定单价'), ('cumulative_commission', '累计提成'), ('segmented_commission', '分段递增提成'), ('jump_point_commission', '跳点提成'), ('combined', '固定价款 + 按实结算')], max_length=30, verbose_name='结算方式')),
                ('fixed_total_price', models.DecimalField(blank=True, decimal_places=2, help_text='方式一：固定总价', max_digits=14, null=True, verbose_name='固定总价')),
                ('fixed_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='方式一：固定单价（元/平方米）', max_digits=12, null=True, verbose_name='固定单价')),
                ('area_scale', models.DecimalField(blank=True, decimal_places=2, help_text='面积规模（平方米），从服务内容移到结算方式', max_digits=15, null=True, verbose_name='面积规模')),
                ('area_type', models.CharField(blank=True, choices=[('drawing_building_area', '图纸建筑面积'), ('drawing_structure_area', '图纸结构面积'), ('planning_building_area', '报规建筑面积'), ('completion_building_area', '竣工建筑面积'), ('survey_area', '测绘面积')], help_text='方式一：固定单价时使用的面积类型', max_length=30, null=True, verbose_name='面积类型')),
                ('cumulative_rate', models.DecimalField(blank=True, decimal_places=2, help_text='方式二：累计提成的取费系数，例如：10.5 表示 10.5%', max_digits=5, null=True, verbose_name='累计提成系数(%)')),
                ('combined_fixed_method', models.CharField(blank=True, choices=[('fixed_total', '固定总价'), ('fixed_unit', '固定单价')], help_text='方式三：固定部分采用的方式', max_length=20, null=True, verbose_name='组合-固定部分方式')),
                ('combined_fixed_total', models.DecimalField(blank=True, decimal_places=2, help_text='方式三：固定部分为固定总价时的金额', max_digits=14, null=True, verbose_name='组合-固定总价')),
                ('combined_fixed_unit', models.DecimalField(blank=True, decimal_places=2, help_text='方式三：固定部分为固定单价时的单价', max_digits=12, null=True, verbose_name='组合-固定单价')),
                ('combined_fixed_area_type', models.CharField(blank=True, choices=[('drawing_building_area', '图纸建筑面积'), ('drawing_structure_area', '图纸结构面积'), ('planning_building_area', '报规建筑面积'), ('completion_building_area', '竣工建筑面积'), ('survey_area', '测绘面积')], help_text='方式三：固定部分为固定单价时的面积类型', max_length=30, null=True, verbose_name='组合-固定面积类型')),
                ('combined_actual_method', models.CharField(blank=True, choices=[('cumulative_commission', '累计提成'), ('segmented_commission', '分段递增提成'), ('jump_point_commission', '跳点提成')], help_text='方式三：按实结算部分采用的方式', max_length=30, null=True, verbose_name='组合-按实结算方式')),
                ('combined_cumulative_rate', models.DecimalField(blank=True, decimal_places=2, help_text='方式三：按实结算部分为累计提成时的系数', max_digits=5, null=True, verbose_name='组合-累计提成系数(%)')),
                ('combined_deduct_fixed', models.BooleanField(default=False, help_text='方式三：按实结算计算时是否应扣除固定价款部分', verbose_name='组合-按实结算是否扣除固定部分')),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, help_text='服务费金额（元）', max_digits=14, null=True, verbose_name='服务费')),
                ('cap_fee', models.DecimalField(blank=True, decimal_places=2, help_text='封顶费金额（元）', max_digits=14, null=True, verbose_name='封顶费')),
                ('has_cap_fee', models.BooleanField(default=False, verbose_name='是否设置封顶费')),
                ('cap_type', models.CharField(blank=True, choices=[('total_cap', '总价封顶'), ('unit_cap', '单价封顶'), ('no_cap', '不设置封顶')], help_text='总价封顶或单价封顶（已废弃，使用cap_fee）', max_length=20, null=True, verbose_name='封顶费类型')),
                ('total_cap_amount', models.DecimalField(blank=True, decimal_places=2, help_text='封顶费为总价封顶时的金额（已废弃，使用cap_fee）', max_digits=14, null=True, verbose_name='总价封顶金额')),
                ('has_minimum_fee', models.BooleanField(default=False, verbose_name='是否设置保底费')),
                ('minimum_fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='保底费金额', max_digits=14, null=True, verbose_name='保底费金额')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, help_text='设为默认后，创建结算时自动选中', verbose_name='是否默认')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务费结算方案',
                'verbose_name_plural': '服务费结算方案',
                'db_table': 'settlement_service_fee_scheme',
                'ordering': ['sort_order', '-created_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceFeeUnitCapDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text='单体名称，例如：1#楼、2#楼等', max_length=200, verbose_name='单体名称')),
                ('cap_unit_price', models.DecimalField(decimal_places=2, help_text='该单体的封顶单价（元/平方米）', max_digits=12, verbose_name='封顶单价')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '单价封顶费明细',
                'verbose_name_plural': '单价封顶费明细',
                'db_table': 'settlement_service_fee_unit_cap_detail',
                'ordering': ['scheme', 'order', 'unit_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SettlementMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='结算方式名称')),
                ('code', models.CharField(choices=[('fixed_total', '总价包干'), ('fixed_unit', '单价包干'), ('segmented_commission', '分段递增提成'), ('segmented_commission_simple', '分段提成'), ('jump_point_commission', '跳点提成'), ('cumulative_commission', '累计提成')], help_text='系统识别代码，不可重复', max_length=50, unique=True, verbose_name='结算方式代码')),
                ('description', models.TextField(blank=True, verbose_name='描述说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '结算方式',
                'verbose_name_plural': '结算方式',
                'db_table': 'settlement_settlement_method',
                'ordering': ['sort_order', 'name'],
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='outputvaluemilestone',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='outputvaluemilestone',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='outputvaluerecord',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='outputvaluerecord',
            name='event',
        ),
        migrations.RemoveField(
            model_name='outputvaluerecord',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='outputvaluerecord',
            name='project',
        ),
        migrations.RemoveField(
            model_name='outputvaluerecord',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='outputvaluerecord',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='contractsettlement',
            options={'managed': False, 'ordering': ['-settlement_date', '-settlement_batch'], 'verbose_name': '合同结算', 'verbose_name_plural': '合同结算'},
        ),
        migrations.AlterModelOptions(
            name='projectsettlement',
            options={'managed': False, 'ordering': ['-settlement_date', '-created_time'], 'verbose_name': '项目结算', 'verbose_name_plural': '项目结算'},
        ),
        migrations.AlterModelOptions(
            name='servicefeerate',
            options={'managed': False, 'ordering': ['contract', 'order', 'min_saving_amount'], 'verbose_name': '服务费率表', 'verbose_name_plural': '服务费率表'},
        ),
        migrations.AlterModelOptions(
            name='settlementitem',
            options={'managed': False, 'ordering': ['settlement', 'order', 'created_time'], 'verbose_name': '结算明细项', 'verbose_name_plural': '结算明细项'},
        ),
        migrations.DeleteModel(
            name='OutputValueEvent',
        ),
        migrations.DeleteModel(
            name='OutputValueMilestone',
        ),
        migrations.DeleteModel(
            name='OutputValueRecord',
        ),
        migrations.DeleteModel(
            name='OutputValueStage',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
