# Generated by Django 4.2.7 on 2025-12-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_management', '0005_remove_settlementitem_settlement__opinion_ef0b16_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['opinion_id'], name='settlement__opinion_ef0b16_idx'),
        ),
    ]
