# Generated by Django 4.2.7 on 2026-02-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_management', '0005_add_goal_model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractsettlement',
            table='settlement_contract_settlement',
        ),
        migrations.AlterModelTable(
            name='projectsettlement',
            table='settlement_project_settlement',
        ),
        migrations.AlterModelTable(
            name='servicefeerate',
            table='settlement_service_fee_rate',
        ),
        migrations.AlterModelTable(
            name='settlementitem',
            table='settlement_settlement_item',
        ),
    ]
