"""
交付客户模块视图 - 拆分后的模块
保持向后兼容，所有视图函数都从子模块导入
"""

# 从各个子模块导入所有视图函数和公共对象
from .common import (
    DELIVERY_MANAGEMENT_MENU,
    _get_active_id_from_path,
    _build_delivery_sidebar_nav,
    _context,
    logger,
)

from .delivery_record import (
    delivery_customer_home,
    report_delivery,
    delivery_list,
    delivery_create,
    delivery_detail,
    delivery_edit,
    delivery_delete,
    delivery_submit,
    delivery_statistics,
    delivery_warnings,
    delivery_approval_list,
    delivery_approval_detail,
    delivery_approval_action,
    delivery_email_list,
    delivery_email_send,
    delivery_express_list,
    delivery_express_send,
    delivery_receipt_list,
    delivery_receipt_confirm,
    delivery_hand_delivery_list,
    delivery_hand_delivery_confirm,
    delivery_receive_list,
    delivery_receive_confirm,
    delivery_feedback_list,
    delivery_feedback_create,
    delivery_achievement_list,
    delivery_achievement_confirm,
    delivery_satisfaction_list,
    delivery_satisfaction_create,
    delivery_satisfaction_statistics,
    delivery_logistics_list,
    delivery_logistics_detail,
    delivery_weekly_report_list,
    delivery_file_prep_list,
    delivery_file_prep_upload,
    delivery_weekly_report_create,
    customer_collaboration,
    customer_portal,
    electronic_signature,
)

from .incoming_document import (
    incoming_document_home,
    incoming_document_list,
    incoming_document_create,
    incoming_document_detail,
    incoming_document_edit,
    incoming_document_delete,
)

from .outgoing_document import (
    outgoing_document_home,
    outgoing_document_list,
    outgoing_document_create,
    get_recipient_units,
    get_recipient_contacts,
    outgoing_document_detail,
    outgoing_document_edit,
    outgoing_document_delete,
    outgoing_document_submit_review,
    outgoing_document_approve,
    outgoing_document_reject,
    outgoing_document_send,
    outgoing_document_complete,
    outgoing_document_archive,
    outgoing_document_record_remedy,
)

from .tracking import (
    outgoing_document_receipt_list,
    outgoing_document_send_from_tracking,
    get_tracking_recipients,
    outgoing_document_tracking_detail,
    update_tracking_express_info,
    hand_delivery_checkin,
    outgoing_document_receipt_confirm,
    outgoing_document_performance_report,
    outgoing_document_audit_trail,
    outgoing_document_audit_query,
    outgoing_document_performance_list,
    outgoing_document_performance_detail,
)

from .express_company import (
    express_company_list,
    express_company_create,
    express_company_detail,
    express_company_edit,
    express_company_delete,
)

from .file_management import (
    file_category_manage,
    file_category_list,
    file_category_create,
    file_template_manage,
)

from .external_api import (
    email_tracking_pixel,
    email_receipt_confirm,
    sms_callback,
    mark_tracking_email_read,
    batch_mark_tracking_email_read,
    confirm_email_received,
    outgoing_document_batch_import,
    outgoing_document_import_template,
)

# 导出所有内容，保持向后兼容
__all__ = [
    # 公共对象
    'DELIVERY_MANAGEMENT_MENU',
    '_get_active_id_from_path',
    '_build_delivery_sidebar_nav',
    '_context',
    'logger',
    # 交付记录
    'delivery_customer_home',
    'report_delivery',
    'delivery_list',
    'delivery_create',
    'delivery_detail',
    'delivery_edit',
    'delivery_delete',
    'delivery_submit',
    'delivery_statistics',
    'delivery_warnings',
    'delivery_approval_list',
    'delivery_approval_detail',
    'delivery_approval_action',
    'delivery_email_list',
    'delivery_email_send',
    'delivery_express_list',
    'delivery_express_send',
    'delivery_receipt_list',
    'delivery_receipt_confirm',
    'delivery_hand_delivery_list',
    'delivery_hand_delivery_confirm',
    'delivery_receive_list',
    'delivery_receive_confirm',
    'delivery_feedback_list',
    'delivery_feedback_create',
    'delivery_achievement_list',
    'delivery_achievement_confirm',
    'delivery_satisfaction_list',
    'delivery_satisfaction_create',
    'delivery_satisfaction_statistics',
    'delivery_logistics_list',
    'delivery_logistics_detail',
    'delivery_weekly_report_list',
    'delivery_file_prep_list',
    'delivery_file_prep_upload',
    'delivery_weekly_report_create',
    'customer_collaboration',
    'customer_portal',
    'electronic_signature',
    # 收文管理
    'incoming_document_home',
    'incoming_document_list',
    'incoming_document_create',
    'incoming_document_detail',
    'incoming_document_edit',
    'incoming_document_delete',
    # 发文管理
    'outgoing_document_home',
    'outgoing_document_list',
    'outgoing_document_create',
    'get_recipient_units',
    'get_recipient_contacts',
    'outgoing_document_detail',
    'outgoing_document_edit',
    'outgoing_document_delete',
    'outgoing_document_submit_review',
    'outgoing_document_approve',
    'outgoing_document_reject',
    'outgoing_document_send',
    'outgoing_document_complete',
    'outgoing_document_archive',
    'outgoing_document_record_remedy',
    # 跟踪功能
    'outgoing_document_receipt_list',
    'outgoing_document_send_from_tracking',
    'get_tracking_recipients',
    'outgoing_document_tracking_detail',
    'update_tracking_express_info',
    'hand_delivery_checkin',
    'outgoing_document_receipt_confirm',
    'outgoing_document_performance_report',
    'outgoing_document_audit_trail',
    'outgoing_document_audit_query',
    'outgoing_document_performance_list',
    'outgoing_document_performance_detail',
    # 外部API
    'mark_tracking_email_read',
    'batch_mark_tracking_email_read',
    'confirm_email_received',
    'outgoing_document_batch_import',
    'outgoing_document_import_template',
    # 快递公司管理
    'express_company_list',
    'express_company_create',
    'express_company_detail',
    'express_company_edit',
    'express_company_delete',
    # 文件管理
    'file_category_manage',
    'file_category_list',
    'file_category_create',
    'file_template_manage',
    # 外部API
    'email_tracking_pixel',
    'email_receipt_confirm',
    'sms_callback',
]
