# Generated by Django 4.2.7 on 2025-12-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_center', '0014_convert_opinion_to_opinion_id'),
    ]

    operations = [
        # 使用SeparateDatabaseAndState来分离数据库操作和状态操作
        # 只更新Django状态，不操作数据库（因为表可能不存在或已经正确）
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 安全删除索引（如果存在）
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS settlement__opinion_555a3a_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='settlementitem',
                    unique_together={('settlement', 'opinion_id')},
                ),
                migrations.AddIndex(
                    model_name='settlementitem',
                    index=models.Index(fields=['opinion_id'], name='settlement__opinion_555a3a_idx'),
                ),
            ],
        ),
    ]
