# Generated by Django 4.2.7 on 2025-12-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_center', '0016_remove_settlementitem_settlement__opinion_555a3a_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['opinion_id'], name='settlement__opinion_555a3a_idx'),
        ),
    ]
