# Generated by Django 4.2.7 on 2026-01-06 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production_management', '0041_alter_projectteamnotification_category'),
        ('settlement_center', '0017_settlementitem_settlement__opinion_555a3a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=100, unique=True, verbose_name='申请单号')),
                ('application_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='申请金额')),
                ('application_date', models.DateField(verbose_name='申请日期')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='期望回款日期')),
                ('reason', models.TextField(verbose_name='申请原因')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('submitted_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_applications', to='production_management.businesscontract', verbose_name='关联合同')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_applications', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payment_applications', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '回款申请',
                'verbose_name_plural': '回款申请',
                'db_table': 'settlement_payment_application',
                'ordering': ['-application_date', '-created_time'],
                'indexes': [models.Index(fields=['application_number'], name='settlement__applica_e0ce10_idx'), models.Index(fields=['contract', 'status'], name='settlement__contrac_3917d8_idx'), models.Index(fields=['application_date'], name='settlement__applica_ee1d73_idx'), models.Index(fields=['status'], name='settlement__status_6bcb42_idx')],
            },
        ),
    ]
