# Generated by Django 4.2.7 on 2026-01-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0003_agentconversation_agentmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentconversation',
            new_name='workflow_ag_user_id_ef27be_idx',
            old_name='workflow_ag_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='agentconversation',
            new_name='workflow_ag_is_acti_71b8c0_idx',
            old_name='workflow_ag_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='agentmessage',
            new_name='workflow_ag_convers_d94559_idx',
            old_name='workflow_ag_convers_idx',
        ),
        migrations.RenameIndex(
            model_name='agentmessage',
            new_name='workflow_ag_created_794bab_idx',
            old_name='workflow_ag_created_idx',
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='applicable_models',
            field=models.CharField(blank=True, help_text='填写业务对象的模型名称（小写），多个用逗号分隔。例如：strategicgoal,plan。留空则需手动指定流程。', max_length=500, verbose_name='适用对象类型'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='code',
            field=models.CharField(blank=True, help_text='系统自动生成，无需手动填写', max_length=100, unique=True, verbose_name='流程代码'),
        ),
    ]
