# Generated by Django 4.2.7 on 2026-01-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0004_rename_workflow_ag_user_id_idx_workflow_ag_user_id_ef27be_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('计划管理', '计划管理'), ('客户管理', '客户管理'), ('交付客户', '交付客户'), ('诉讼管理', '诉讼管理'), ('生产管理', '生产管理'), ('财务管理', '财务管理'), ('人事管理', '人事管理'), ('行政管理', '行政管理'), ('风险管理', '风险管理'), ('档案管理', '档案管理'), ('其他', '其他')], help_text='选择流程所属的功能模块', max_length=100, verbose_name='流程分类'),
        ),
    ]
