# Generated by Django 4.2.7 on 2026-01-07 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow_engine', '0005_alter_workflowtemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalinstance',
            name='cc_users',
            field=models.ManyToManyField(blank=True, help_text='审批完成后会通知这些人员', related_name='cc_approval_instances', to=settings.AUTH_USER_MODEL, verbose_name='抄送人员'),
        ),
    ]
