# Generated by Django 4.2.7 on 2026-01-07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow_engine', '0006_add_cc_users_to_approval_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='default_cc_users',
            field=models.ManyToManyField(
                blank=True,
                help_text='创建审批实例时会自动继承这些抄送人员。如果创建时明确指定了抄送人员，则使用指定的；否则使用此默认值。',
                related_name='default_cc_workflows',
                to=settings.AUTH_USER_MODEL,
                verbose_name='默认抄送人员'
            ),
        ),
    ]

