# Generated by Django 4.2.7 on 2026-01-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0007_add_default_cc_users_to_workflow_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='sub_workflow',
            field=models.ForeignKey(
                blank=True,
                help_text='审批通过后自动触发的子流程。如果设置了子流程，当主流程审批通过时，会自动启动子流程。',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='parent_workflows',
                to='workflow_engine.workflowtemplate',
                verbose_name='子流程模板'
            ),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='sub_workflow_trigger_condition',
            field=models.CharField(
                blank=True,
                choices=[
                    ('on_approved', '审批通过时触发'),
                    ('on_rejected', '审批驳回时触发'),
                    ('on_completed', '审批完成时触发（通过或驳回）')
                ],
                default='on_approved',
                help_text='选择子流程的触发条件',
                max_length=50,
                verbose_name='子流程触发条件'
            ),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='parent_instance',
            field=models.ForeignKey(
                blank=True,
                help_text='如果此审批实例是由父流程触发的子流程，则关联到父流程实例',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='child_instances',
                to='workflow_engine.approvalinstance',
                verbose_name='父流程实例'
            ),
        ),
    ]

