# Generated by Django 4.2.7 on 2026-02-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow_engine', '0007_alter_workflowtemplate_applicable_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交审批'), ('start', '启动'), ('cancel', '取消'), ('approve', '审批'), ('reject', '驳回'), ('withdraw', '撤回')], default='submit', help_text='选择操作类型，例如：submit（提交审批）、start（启动）、cancel（取消）等', max_length=50, verbose_name='操作类型')),
                ('priority', models.IntegerField(default=0, help_text='数字越大优先级越高。当同一业务对象类型和操作类型有多条配置时，选择优先级最高的启用配置', verbose_name='优先级')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='只有启用的配置才会生效', verbose_name='是否启用')),
                ('note', models.TextField(blank=True, help_text='配置说明或备注信息', verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_type', models.ForeignKey(help_text='选择要绑定的业务对象类型，例如：loanapplication（借款申请）、sealusage（用印申请）等', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='业务对象类型')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflow_bindings', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workflow_bindings', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('workflow_template', models.ForeignKey(help_text='选择要绑定的流程模板', on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='workflow_engine.workflowtemplate', verbose_name='流程模板')),
            ],
            options={
                'verbose_name': '流程模板绑定配置',
                'verbose_name_plural': '流程模板绑定配置',
                'db_table': 'workflow_binding',
                'ordering': ['-priority', '-created_time'],
                'indexes': [models.Index(fields=['content_type', 'action', 'is_active'], name='workflow_bi_content_54faec_idx'), models.Index(fields=['is_active'], name='workflow_bi_is_acti_c9c129_idx')],
            },
        ),
    ]
