# Generated by Django 4.2.7 on 2026-02-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0008_add_workflow_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalnode',
            name='approver_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON格式的审批人规则配置参数，例如：{"levels": 2} 用于多级上级审批', verbose_name='审批人规则配置'),
        ),
    ]
