# Generated by Django 4.2.7 on 2026-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0009_add_approver_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalnode',
            name='approver_type',
            field=models.CharField(blank=True, choices=[('role', '指定角色'), ('department', '指定部门'), ('department_manager', '部门经理'), ('creator', '创建人'), ('creator_manager', '创建人直属上级'), ('creator_manager_chain', '创建人多级上级')], max_length=30, verbose_name='审批人类型'),
        ),
    ]
