# Generated by Django 6.0 on 2025-12-23 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0011_rename_file_catego_stage_s_idx_file_catego_stage_739c10_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingDocumentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', '草稿'), ('reviewing', '审核中'), ('approved', '已批准'), ('sent', '已发出'), ('completed', '已完成'), ('archived', '已归档')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('draft', '草稿'), ('reviewing', '审核中'), ('approved', '已批准'), ('sent', '已发出'), ('completed', '已完成'), ('archived', '已归档')], max_length=20, verbose_name='目标状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_document_status_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='delivery_customer.outgoingdocument', verbose_name='发文')),
            ],
            options={
                'verbose_name': '发文状态流转日志',
                'verbose_name_plural': '发文状态流转日志',
                'db_table': 'outgoing_document_status_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='outgoing_do_documen_2f5106_idx')],
            },
        ),
    ]
