# Generated by Django 6.0 on 2025-12-23 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0051_remove_filter_collapse_feature'),
        ('delivery_customer', '0012_add_outgoing_document_status_log'),
        ('production_management', '0032_remove_contractservicecontent_contract_se_contrac_35b26d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingdocument',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='正式签收确认时间', null=True, verbose_name='签收确认时间'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='delay_days',
            field=models.IntegerField(default=0, help_text='延迟天数', verbose_name='延迟天数'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='delay_reason',
            field=models.TextField(blank=True, verbose_name='延迟原因'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='e_sign_contract_id',
            field=models.CharField(blank=True, help_text='电子签平台的合同ID', max_length=200, verbose_name='电子签合同ID'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='e_sign_document_hash',
            field=models.CharField(blank=True, help_text='用于验证文档完整性', max_length=256, verbose_name='电子签文档哈希'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='e_sign_status',
            field=models.CharField(blank=True, help_text='待签、已签、拒绝、过期等', max_length=50, verbose_name='电子签状态'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='e_sign_url',
            field=models.URLField(blank=True, help_text='电子签签署链接', max_length=500, verbose_name='电子签链接'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='e_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='电子签完成时间'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='email_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='邮件阅读时间'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='邮件发送时间'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='email_tracking_id',
            field=models.CharField(blank=True, help_text='邮件追踪标识', max_length=200, verbose_name='邮件追踪ID'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='expected_confirm_date',
            field=models.DateField(blank=True, help_text='预期签收确认日期', null=True, verbose_name='预期签收日期'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='expected_receive_date',
            field=models.DateField(blank=True, help_text='预期收文单位接收日期', null=True, verbose_name='预期接收日期'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='express_company',
            field=models.CharField(blank=True, help_text='快递公司名称', max_length=100, verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='express_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='快递状态更新时间'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='express_number',
            field=models.CharField(blank=True, db_index=True, help_text='快递单号，用于物流跟踪', max_length=100, verbose_name='快递单号'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='express_status',
            field=models.CharField(blank=True, help_text='在途、已签收、异常等', max_length=50, verbose_name='快递状态'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='is_delayed',
            field=models.BooleanField(db_index=True, default=False, help_text='是否超过预期送达时间', verbose_name='是否延迟'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='is_receipt_confirmed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已签收'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='receipt_by',
            field=models.CharField(blank=True, help_text='实际签收人姓名', max_length=100, verbose_name='签收人'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='receipt_comment',
            field=models.TextField(blank=True, help_text='签收时的备注信息', verbose_name='签收备注'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='receipt_confirmed_by',
            field=models.ForeignKey(blank=True, help_text='系统内确认签收的操作人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_confirmed_outgoing_documents', to=settings.AUTH_USER_MODEL, verbose_name='签收确认操作人'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='receipt_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='签收人邮箱'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='receipt_method',
            field=models.CharField(blank=True, help_text='纸质签收、电子签收、邮件确认等', max_length=50, verbose_name='签收方式'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='receipt_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='签收人电话'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='receipt_signature',
            field=models.ImageField(blank=True, help_text='签收凭证图片或电子签名', null=True, upload_to='outgoing_documents/receipts/%Y/%m/%d/', verbose_name='签收凭证'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='收文单位实际接收时间', null=True, verbose_name='接收时间'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='remedy_action',
            field=models.TextField(blank=True, help_text='针对延迟采取的补救措施', verbose_name='补救措施'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='remedy_action_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='补救措施执行时间'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='remedy_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remedy_action_outgoing_documents', to=settings.AUTH_USER_MODEL, verbose_name='补救措施执行人'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='responsible_person',
            field=models.ForeignKey(blank=True, help_text='发文责任人，关联绩效记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_outgoing_documents', to=settings.AUTH_USER_MODEL, verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='warning_sent',
            field=models.BooleanField(default=False, help_text='是否已发送延迟预警', verbose_name='是否已发送预警'),
        ),
        migrations.AddField(
            model_name='outgoingdocument',
            name='warning_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预警发送时间'),
        ),
        migrations.AddIndex(
            model_name='outgoingdocument',
            index=models.Index(fields=['is_receipt_confirmed', '-confirmed_at'], name='outgoing_do_is_rece_ba36ae_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingdocument',
            index=models.Index(fields=['express_number'], name='outgoing_do_express_662dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingdocument',
            index=models.Index(fields=['is_delayed', 'warning_sent'], name='outgoing_do_is_dela_8cfe23_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingdocument',
            index=models.Index(fields=['responsible_person', '-sent_at'], name='outgoing_do_respons_6e84ab_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingdocument',
            index=models.Index(fields=['expected_receive_date', 'is_delayed'], name='outgoing_do_expecte_e0331d_idx'),
        ),
    ]
