# Generated by Django 4.2.7 on 2025-12-25 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_customer', '0013_outgoingdocument_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='如：邮件、快递、现场送达、易签宝', max_length=50, unique=True, verbose_name='报送方式名称')),
                ('code', models.CharField(db_index=True, help_text='用于系统识别，如：email、express、hand_delivery、yisign', max_length=50, unique=True, verbose_name='报送方式代码')),
                ('description', models.TextField(blank=True, help_text='报送方式的详细说明', verbose_name='描述')),
                ('sort_order', models.IntegerField(db_index=True, default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='禁用后不会在创建发文时显示', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_methods', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报送方式',
                'verbose_name_plural': '报送方式',
                'db_table': 'delivery_method',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='delivery_me_is_acti_2ae1cb_idx')],
            },
        ),
    ]
