# Generated by Django migration

from django.db import migrations


def create_default_delivery_methods(apps, schema_editor):
    """创建默认的报送方式"""
    DeliveryMethod = apps.get_model('delivery_customer', 'DeliveryMethod')
    
    # 默认报送方式列表
    default_methods = [
        {'name': '邮件', 'code': 'email', 'sort_order': 1},
        {'name': '快递', 'code': 'express', 'sort_order': 2},
        {'name': '现场送达', 'code': 'hand_delivery', 'sort_order': 3},
        {'name': '易签宝', 'code': 'yisign', 'sort_order': 4},
    ]
    
    # 创建报送方式（如果不存在）
    for method_data in default_methods:
        DeliveryMethod.objects.get_or_create(
            code=method_data['code'],
            defaults={
                'name': method_data['name'],
                'sort_order': method_data['sort_order'],
                'is_active': True,
            }
        )


def reverse_create_default_delivery_methods(apps, schema_editor):
    """删除默认的报送方式（可选，用于回滚）"""
    DeliveryMethod = apps.get_model('delivery_customer', 'DeliveryMethod')
    DeliveryMethod.objects.filter(code__in=['email', 'express', 'hand_delivery', 'yisign']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0014_deliverymethod'),
    ]

    operations = [
        migrations.RunPython(
            create_default_delivery_methods,
            reverse_create_default_delivery_methods
        ),
    ]
