# Generated by Django 4.2.7 on 2025-12-25 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_customer', '0015_auto_20251225_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingDocumentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('sent', '已发送'), ('in_transit', '运输中'), ('delivered', '已送达'), ('received', '已接收'), ('confirmed', '已确认'), ('completed', '已完成'), ('failed', '发送失败'), ('rejected', '已拒收'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='跟踪状态')),
                ('email_subject', models.CharField(blank=True, max_length=500, verbose_name='邮件主题')),
                ('email_to', models.EmailField(blank=True, max_length=255, verbose_name='收件邮箱')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='邮件发送时间')),
                ('email_read_at', models.DateTimeField(blank=True, null=True, verbose_name='邮件阅读时间')),
                ('email_tracking_id', models.CharField(blank=True, max_length=200, verbose_name='邮件追踪ID')),
                ('email_message_id', models.CharField(blank=True, help_text='用于邮件跟踪', max_length=500, verbose_name='邮件消息ID')),
                ('express_company', models.CharField(blank=True, max_length=100, verbose_name='快递公司')),
                ('express_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='快递单号')),
                ('express_status', models.CharField(blank=True, max_length=50, verbose_name='快递状态')),
                ('express_last_update', models.DateTimeField(blank=True, null=True, verbose_name='快递状态更新时间')),
                ('express_tracking_data', models.JSONField(blank=True, default=dict, help_text='存储快递100 API返回的完整跟踪数据', verbose_name='快递跟踪数据')),
                ('hand_delivery_location', models.CharField(blank=True, help_text='GPS定位地址', max_length=200, verbose_name='送达地点')),
                ('hand_delivery_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('hand_delivery_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('hand_delivery_photo', models.ImageField(blank=True, null=True, upload_to='outgoing_documents/hand_delivery/%Y/%m/%d/', verbose_name='送达照片')),
                ('hand_delivery_checkin_at', models.DateTimeField(blank=True, null=True, verbose_name='打卡时间')),
                ('yisign_contract_id', models.CharField(blank=True, max_length=200, verbose_name='易签宝合同ID')),
                ('yisign_contract_url', models.URLField(blank=True, max_length=500, verbose_name='易签宝合同链接')),
                ('yisign_status', models.CharField(blank=True, help_text='待签、已签、拒绝、过期等', max_length=50, verbose_name='易签宝状态')),
                ('yisign_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='易签宝签署时间')),
                ('yisign_signed_by', models.CharField(blank=True, max_length=100, verbose_name='易签宝签署人')),
                ('yisign_callback_data', models.JSONField(blank=True, default=dict, help_text='存储易签宝网站反馈的数据', verbose_name='易签宝回调数据')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, help_text='发送失败或异常时的错误信息', verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, help_text='发送失败后的重试次数', verbose_name='重试次数')),
                ('last_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='最后重试时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracking_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_records', to='delivery_customer.deliverymethod', verbose_name='报送方式')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='delivery_customer.outgoingdocument', verbose_name='关联发文')),
                ('hand_delivery_checkin_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hand_delivery_checkins', to=settings.AUTH_USER_MODEL, verbose_name='送达人')),
            ],
            options={
                'verbose_name': '发文跟踪记录',
                'verbose_name_plural': '发文跟踪记录',
                'db_table': 'outgoing_document_tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'delivery_method'], name='outgoing_do_documen_8a5bbc_idx'), models.Index(fields=['status', 'created_at'], name='outgoing_do_status_078c90_idx'), models.Index(fields=['express_number'], name='outgoing_do_express_9347e6_idx')],
                'unique_together': {('document', 'delivery_method')},
            },
        ),
    ]
