# Generated by Django 4.2.7 on 2025-12-30 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_customer', '0016_add_outgoing_document_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingdocumenttracking',
            name='email_received_attachment',
            field=models.FileField(blank=True, help_text='邮件报送方式：收件人确认已接收时上传的证明附件（必填）', null=True, upload_to='outgoing_documents/email_received_attachments/%Y/%m/%d/', verbose_name='接收确认附件'),
        ),
        migrations.AddField(
            model_name='outgoingdocumenttracking',
            name='email_received_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认接收时间'),
        ),
        migrations.AddField(
            model_name='outgoingdocumenttracking',
            name='email_received_confirmed_by',
            field=models.ForeignKey(blank=True, help_text='执行确认接收操作的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_received_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='确认接收操作人'),
        ),
    ]
