# Generated by Django 4.2.7 on 2025-12-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0017_outgoingdocumenttracking_email_received_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingdocumenttracking',
            name='express_reject_detail',
            field=models.TextField(blank=True, help_text='退回原因的详细说明，从快递跟踪信息中提取', verbose_name='退回详情'),
        ),
        migrations.AddField(
            model_name='outgoingdocumenttracking',
            name='express_reject_reason',
            field=models.CharField(blank=True, choices=[('contact_failed', '联系不到收件人'), ('recipient_refused', '收件人拒收'), ('address_error', '地址错误/不详'), ('recipient_not_found', '收件人不存在'), ('delivery_failed', '派送失败'), ('other', '其他原因')], help_text='快递退回或拒收的具体原因', max_length=50, verbose_name='退回原因'),
        ),
        migrations.AddField(
            model_name='outgoingdocumenttracking',
            name='express_reject_time',
            field=models.DateTimeField(blank=True, help_text='快递退回或拒收的时间', null=True, verbose_name='退回时间'),
        ),
    ]
