# Generated by Django 4.2.7 on 2026-01-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_customer', '0020_add_sms_fields_to_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingdocumenttracking',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='短信发送时间'),
        ),
    ]
