# Generated by Django 4.2.7 on 2025-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_management', '0001_initial'),
        ('system_management', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='permission_management.permissionitem', verbose_name='业务权限'),
        ),
    ]
