# Generated by Django 4.2.7 on 2026-01-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0009_merge_20251208_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['user_type', 'code'], 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AddField(
            model_name='role',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', '通用角色'), ('internal', '咨询单位'), ('client_owner', '委托单位'), ('design_partner', '设计单位'), ('control_partner', '过控单位')], default='', help_text='留空表示通用角色，适用于所有单位类别', max_length=20, verbose_name='适用单位类别'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, verbose_name='角色编码'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('code', 'user_type')},
        ),
    ]
