# Generated by Django 4.2.7 on 2026-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0010_add_role_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(blank=True, help_text='留空将自动生成', max_length=50, verbose_name='角色编码'),
        ),
    ]
