# Generated by Django 4.2.7 on 2026-01-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0011_make_role_code_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
    ]
