# Generated by Django 4.2.7 on 2026-02-05 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0012_rename_system_fee_status_8a3f2d_idx_system_feed_status_5259c5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='用于审批流程中的"创建人上级"规则，组织变化时只需更新此字段，无需修改流程模板', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL, verbose_name='直属上级'),
        ),
    ]
