# Generated by Django 4.2.7 on 2026-01-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0041_alter_projectteamnotification_category'),
        ('system_management', '0012_remove_role_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['user_type', 'profession', 'code'], 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='role',
            name='profession',
            field=models.ForeignKey(blank=True, help_text='仅工程师类角色需要设置专业，用于区分不同专业的工程师', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='production_management.serviceprofession', verbose_name='所属专业'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('code', 'user_type', 'profession')},
        ),
    ]
