# Generated by Django 4.2.7 on 2026-02-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0013_add_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='P0-2: 用户所属公司，用于多公司数据隔离', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='system_management.ourcompany', verbose_name='所属公司'),
        ),
    ]
