# Generated by Django 4.2.7 on 2026-01-08 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0013_add_role_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ORG_CHANGE', '归属变更')], max_length=50, verbose_name='操作类型')),
                ('object_type', models.CharField(max_length=100, verbose_name='对象类型')),
                ('object_id', models.CharField(max_length=64, verbose_name='对象ID')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='变更内容')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '操作审计日志',
                'verbose_name_plural': '操作审计日志',
                'db_table': 'system_audit_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'object_type', 'object_id'], name='system_audi_action_2e7590_idx'), models.Index(fields=['actor', 'created_at'], name='system_audi_actor_i_da15d8_idx')],
            },
        ),
    ]
