# Generated by Django 4.2.7 on 2026-01-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0014_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ORG_CHANGE', '归属变更'), ('CONTRACT_ACTION', '合同关键动作')], max_length=50, verbose_name='操作类型'),
        ),
    ]
