# Generated by Django 4.2.7 on 2026-01-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0015_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ORG_CHANGE', '归属变更'), ('CONTRACT_ACTION', '合同关键动作'), ('PLAN_ACTION', '计划关键动作'), ('GOAL_ACTION', '目标关键动作')], max_length=50, verbose_name='操作类型'),
        ),
    ]
