# Generated by Django 4.2.7 on 2025-12-24 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0052_add_project_number_to_business_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOpportunityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='opportunity_attachments/%Y/%m/%d/', verbose_name='附件文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file_type', models.CharField(blank=True, help_text='如：业务委托书、中标通知书等', max_length=50, verbose_name='文件类型')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('uploaded_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '商机附件',
                'verbose_name_plural': '商机附件',
                'db_table': 'business_opportunity_attachment',
                'ordering': ['-uploaded_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='businessopportunity',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='businessopportunity',
            name='business_op_opportu_247937_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessopportunity',
            name='business_op_status_97cb9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessopportunity',
            name='business_op_busines_690fca_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessopportunity',
            name='business_op_expecte_ffe177_idx',
        ),
        migrations.AlterField(
            model_name='businessopportunity',
            name='project_number',
            field=models.CharField(blank=True, help_text='赢单后自动生成：YYYYMMDD-NNNN，不可修改', max_length=50, null=True, unique=True, verbose_name='项目编号'),
        ),
        migrations.AlterModelTable(
            name='businessopportunity',
            table=None,
        ),
        migrations.AddField(
            model_name='businessopportunityattachment',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='customer_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AddField(
            model_name='businessopportunityattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_opportunity_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddIndex(
            model_name='businessopportunityattachment',
            index=models.Index(fields=['opportunity'], name='business_op_opportu_2af109_idx'),
        ),
        migrations.AddIndex(
            model_name='businessopportunityattachment',
            index=models.Index(fields=['file_type'], name='business_op_file_ty_1c1b47_idx'),
        ),
    ]
