# Generated by Django migration
# 为已存在的赢单商机创建对应的项目

from django.db import migrations
from django.db import transaction
from django.conf import settings
import logging

logger = logging.getLogger(__name__)


def create_projects_for_won_opportunities(apps, schema_editor):
    """
    为所有已存在的赢单商机创建对应的项目
    项目编号 = 商机编号（opportunity_number）
    """
    BusinessOpportunity = apps.get_model('customer_management', 'BusinessOpportunity')
    Project = apps.get_model('production_management', 'Project')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # 获取所有状态为赢单的商机
    won_opportunities = BusinessOpportunity.objects.filter(
        status='won',
        opportunity_number__isnull=False
    ).exclude(opportunity_number='')
    
    created_count = 0
    skipped_count = 0
    error_count = 0
    
    # 获取系统用户（用于创建人字段，如果商机没有创建人）
    system_user = None
    try:
        system_user = User.objects.filter(is_superuser=True).first()
        if not system_user:
            system_user = User.objects.first()
    except Exception:
        pass
    
    for opportunity in won_opportunities:
        try:
            project_number = opportunity.opportunity_number
            
            # 检查项目是否已存在
            existing_project = Project.objects.filter(project_number=project_number).first()
            if existing_project:
                skipped_count += 1
                logger.info(f'项目已存在，跳过：项目编号={project_number}')
                continue
            
            # 准备项目数据
            project_data = {
                'project_number': project_number,
                'name': opportunity.project_name or opportunity.name or '未命名项目',
                'client': opportunity.client,
                'service_type': opportunity.service_type,
                'status': 'draft',  # 初始状态为草稿
            }
            
            # 设置创建人
            if opportunity.created_by:
                project_data['created_by'] = opportunity.created_by
            elif system_user:
                project_data['created_by'] = system_user
            
            # 如果商机有项目地址，设置到项目描述中
            if opportunity.project_address:
                project_data['description'] = f'项目地址：{opportunity.project_address}'
            
            # 创建项目
            with transaction.atomic():
                Project.objects.create(**project_data)
                created_count += 1
                logger.info(f'为赢单商机创建项目：项目编号={project_number}, 项目名称={project_data["name"]}')
                
        except Exception as e:
            error_count += 1
            logger.error(f'为商机创建项目失败：商机ID={opportunity.id}, 商机编号={opportunity.opportunity_number}, 错误={str(e)}')
    
    logger.info(f'迁移完成：创建={created_count}, 跳过={skipped_count}, 错误={error_count}')


def reverse_create_projects(apps, schema_editor):
    """
    回滚操作：删除由赢单商机创建的项目
    """
    BusinessOpportunity = apps.get_model('customer_management', 'BusinessOpportunity')
    Project = apps.get_model('production_management', 'Project')
    
    # 获取所有赢单商机的编号
    won_opportunity_numbers = set(
        BusinessOpportunity.objects.filter(
            status='won',
            opportunity_number__isnull=False
        ).exclude(opportunity_number='').values_list('opportunity_number', flat=True)
    )
    
    # 删除对应的项目
    if won_opportunity_numbers:
        deleted_count = Project.objects.filter(project_number__in=won_opportunity_numbers).delete()[0]
        logger.info(f'回滚：删除了 {deleted_count} 个项目')


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0053_add_business_opportunity_attachment'),
    ]

    operations = [
        migrations.RunPython(
            create_projects_for_won_opportunities,
            reverse_create_projects,
        ),
    ]

