# Generated by Django 4.2.7 on 2025-12-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0054_create_projects_for_won_opportunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='customer_number',
            field=models.CharField(blank=True, help_text='系统自动生成：KH-YYYYMMDD-NNNN', max_length=50, null=True, unique=True, verbose_name='客户编号'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['customer_number'], name='customer_cl_custome_0c1a06_idx'),
        ),
    ]
