# Generated by Django 4.2.7 on 2025-12-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0055_add_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='contact_number',
            field=models.CharField(blank=True, help_text='格式：LXR-YYYYMMDD-NNNN，系统自动生成', max_length=20, null=True, unique=True, verbose_name='联系人编号'),
        ),
    ]
