# Generated by Django 4.2.7 on 2025-12-26 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow_engine', '0002_alter_approvalinstance_content_type_and_more'),
        ('customer_management', '0056_clientcontact_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfoChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('basic_info', '基本信息变更'), ('contact_info', '联系信息变更'), ('financial_info', '财务信息变更'), ('other', '其他信息变更')], default='basic_info', max_length=20, verbose_name='变更类型')),
                ('change_reason', models.TextField(help_text='说明为什么要进行此次变更', verbose_name='变更原因')),
                ('change_content', models.JSONField(default=dict, help_text='JSON格式存储变更前后的值', verbose_name='变更内容')),
                ('approval_status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='审批状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approval_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_info_changes', to='workflow_engine.approvalinstance', verbose_name='审批实例')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_changes', to='customer_management.client', verbose_name='关联客户')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_client_info_changes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户信息变更记录',
                'verbose_name_plural': '客户信息变更记录',
                'db_table': 'customer_client_info_change',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['client', 'approval_status'], name='customer_cl_client__79e26d_idx'), models.Index(fields=['change_type'], name='customer_cl_change__31e62c_idx'), models.Index(fields=['created_time'], name='customer_cl_created_11e72a_idx')],
            },
        ),
    ]
