# Generated by Django 4.2.7 on 2026-01-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity_management', '0001_initial'),
        ('production_management', '0042_alter_businesscontract_opportunity'),
        ('customer_management', '0057_remove_biddingquotation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationletter',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_letters', to='opportunity_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AlterField(
            model_name='contacttracking',
            name='related_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_trackings', to='opportunity_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AlterField(
            model_name='customerfiling',
            name='related_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_filings', to='opportunity_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AlterField(
            model_name='customerwarehouseapplication',
            name='related_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_warehouse_applications', to='opportunity_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AlterField(
            model_name='salesactivity',
            name='related_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='opportunity_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='related_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_plans', to='opportunity_management.businessopportunity', verbose_name='关联商机'),
        ),
        migrations.DeleteModel(
            name='BiddingQuotation',
        ),
        migrations.DeleteModel(
            name='BusinessNegotiation',
        ),
        migrations.DeleteModel(
            name='BusinessOpportunity',
        ),
        migrations.DeleteModel(
            name='CustomerRequirementCommunication',
        ),
        migrations.DeleteModel(
            name='OpportunityApproval',
        ),
        migrations.DeleteModel(
            name='OpportunityFiling',
        ),
        migrations.DeleteModel(
            name='OpportunityFollowUp',
        ),
        migrations.DeleteModel(
            name='OpportunityQuotation',
        ),
        migrations.DeleteModel(
            name='OpportunityStatusLog',
        ),
        migrations.DeleteModel(
            name='QuotationRule',
        ),
    ]
