# Generated by Django 4.2.7 on 2026-01-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0057_clientinfochange'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('unified_credit_code__isnull', False), models.Q(('unified_credit_code', ''), _negated=True)), fields=('unified_credit_code',), name='unique_unified_credit_code'),
        ),
    ]
