# Generated by Django 4.2.7 on 2026-02-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0002_add_goal_model'),
        ('customer_management', '0058_alter_authorizationletter_opportunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractnegotiation',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='可选，如果洽谈时合同尚未创建可留空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='contract_management.businesscontract', verbose_name='关联合同'),
        ),
    ]
