# Generated by Django 4.2.7 on 2026-01-08 01:03

from django.db import migrations


def fill_default_company_department(apps, schema_editor):
    """回填历史数据：将空值填充为默认公司（维海科技）和部门（总部）"""
    Company = apps.get_model("org", "Company")
    Department = apps.get_model("org", "Department")
    Client = apps.get_model("customer_management", "Client")

    try:
        company = Company.objects.get(code="VIHHI")
        dept = Department.objects.get(company=company, name="总部", parent=None)
        
        # 回填 company 为空的数据
        Client.objects.filter(company__isnull=True).update(company=company)
        # 回填 department 为空的数据
        Client.objects.filter(department__isnull=True).update(department=dept)
    except (Company.DoesNotExist, Department.DoesNotExist):
        # 如果默认公司/部门不存在，跳过回填（可能是在初始化阶段）
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('customer_management', '0059_client_company_client_department'),
    ]

    operations = [
        migrations.RunPython(fill_default_company_department, migrations.RunPython.noop),
    ]
