# Generated by Django 4.2.7 on 2026-02-05 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_management', '0043_remove_base_data_models'),
        ('opportunity_management', '0007_add_opportunity_project_fk'),
        ('system_management', '0012_rename_system_fee_status_8a3f2d_idx_system_feed_status_5259c5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0058_alter_authorizationletter_opportunity_and_more'),
        ('contract_management', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, help_text='唯一标识，留空将自动生成（格式：VIH-CON-YYYY-NNNN）', max_length=100, null=True, unique=True, verbose_name='合同编号')),
                ('project_number', models.CharField(blank=True, help_text='自动生成：YYYYMMDD-0000，可手动修改。项目编号须保持唯一性', max_length=50, null=True, unique=True, verbose_name='项目编号')),
                ('contract_name', models.CharField(blank=True, help_text='如未填写，将使用合同编号', max_length=200, verbose_name='合同名称')),
                ('contract_type', models.CharField(choices=[('strategic', '战略合同'), ('framework', '框架合同'), ('project', '项目合同'), ('intent', '意向合同'), ('supplement', '补充协议'), ('change', '变更协议'), ('termination', '终止协议'), ('other', '其他')], default='project', max_length=20, verbose_name='合同类型')),
                ('status', models.CharField(choices=[('draft', '合同草稿'), ('dispute', '合同争议'), ('finalized', '合同定稿'), ('party_b_signed', '我方签章'), ('signed', '对方签章'), ('effective', '已生效'), ('executing', '执行中'), ('completed', '已完成'), ('terminated', '已终止'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='合同状态')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额（含税）')),
                ('contract_amount_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同税额')),
                ('contract_amount_excl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额（不含税）')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=6.0, help_text='默认6%，可调整', max_digits=5, verbose_name='税率(%)')),
                ('settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已结算金额')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已回款金额')),
                ('unpaid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='自动计算：合同金额-已回款金额', max_digits=12, null=True, verbose_name='未回款金额')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='合同签订日期')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='合同生效日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='合同开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='合同结束日期')),
                ('contract_period', models.IntegerField(blank=True, help_text='自动计算：结束日期-开始日期', null=True, verbose_name='合同期限（天）')),
                ('party_a_name', models.CharField(blank=True, max_length=200, verbose_name='甲方名称')),
                ('party_a_contact', models.CharField(blank=True, max_length=100, verbose_name='甲方联系人')),
                ('party_b_name', models.CharField(blank=True, default='四川维海科技有限公司', max_length=200, verbose_name='乙方名称')),
                ('party_b_contact', models.CharField(blank=True, max_length=100, verbose_name='乙方联系人')),
                ('structure_type', models.CharField(blank=True, choices=[('shear_wall', '剪力墙结构'), ('frame', '框架结构'), ('steel', '钢结构'), ('other', '其他')], help_text='项目的结构形式，用于合同管理和维护', max_length=50, null=True, verbose_name='结构形式')),
                ('design_unit_category', models.CharField(blank=True, choices=[('class_1', '一类设计院'), ('class_2', '二类设计院'), ('class_3', '三类设计院'), ('class_4', '四类设计院')], help_text='设计单位的分类等级，用于合同管理和维护', max_length=20, null=True, verbose_name='设计单位分类')),
                ('service_type', models.CharField(blank=True, choices=[('result_optimization', '结果优化'), ('process_optimization', '过程优化')], help_text='服务类型调整（T1）：结果优化：1.0，过程优化：1.5', max_length=30, null=True, verbose_name='服务类型')),
                ('project_type', models.CharField(blank=True, choices=[('residential', '住宅'), ('complex', '综合体'), ('industrial', '工业厂房'), ('office', '写字楼'), ('commercial', '商业'), ('school', '学校'), ('hospital', '医院'), ('municipal', '市政'), ('other', '其他')], help_text='项目业态调整（T2）：住宅：1.0，综合体：1.2，工业厂房：1.10，写字楼=1.15，商业=1.3，学校=1.05，医院=1.25，市政=1.4，其他=1.0', max_length=30, null=True, verbose_name='项目业态')),
                ('service_professions', models.JSONField(blank=True, default=list, help_text='服务专业调整（T3）：结构：0.32；构造：0.48，电气：0.14，给排水：0.06，其他专业每增加一个，调整系数增加0.1，但总系数不超过1.5', verbose_name='服务专业')),
                ('drawing_stage', models.CharField(blank=True, choices=[('construction_unaudited', '施工图（未审图）'), ('construction_audited', '施工图（已审图）'), ('preliminary_scheme', '初步方案'), ('detailed_scheme', '详细方案'), ('preliminary_design', '初步设计'), ('extended_preliminary', '扩初设计'), ('construction_stage', '施工阶段'), ('special_design', '专项设计')], help_text='图纸阶段调整（T5）：施工图（未审图）：1.0，施工图（已审图）：0.6，初步方案：1.5，详细方案：1.4，初步设计：1.3，扩初设计：1.2，施工阶段：0.5，专项设计：1.0', max_length=30, null=True, verbose_name='图纸阶段')),
                ('basement_area', models.DecimalField(blank=True, decimal_places=2, help_text='用于计算地下面积占比调整（T6）', max_digits=12, null=True, verbose_name='地下室面积（㎡）')),
                ('total_building_area', models.DecimalField(blank=True, decimal_places=2, help_text='用于计算地下面积占比调整（T6）', max_digits=12, null=True, verbose_name='总建筑面积（㎡）')),
                ('comprehensive_adjustment_coefficient', models.DecimalField(blank=True, decimal_places=2, help_text='自动计算：T1*T2*T3*T4*T5*T6*T7，最大不超过2.0', max_digits=5, null=True, verbose_name='综合调整系数')),
                ('description', models.TextField(blank=True, verbose_name='合同描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='合同审批人')),
                ('business_manager', models.ForeignKey(blank=True, help_text='默认为填写人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='商务经理')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customer_management.client', verbose_name='客户')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, help_text='默认填写人的部门', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='system_management.department', verbose_name='部门')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='opportunity_management.businessopportunity', verbose_name='关联商机')),
                ('parent_contract', models.ForeignKey(blank=True, help_text='用于补充协议、变更协议关联主合同', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_contracts', to='contract_management.businesscontract', verbose_name='主合同')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='production_management.project', verbose_name='关联项目')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='合同签订人')),
            ],
            options={
                'verbose_name': '商务合同',
                'verbose_name_plural': '商务合同',
                'db_table': 'business_contract',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ResultFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('result_optimization', '结果优化'), ('process_optimization', '过程优化'), ('full_process_consulting', '全过程咨询')], db_index=True, max_length=50, verbose_name='服务类别')),
                ('code', models.CharField(help_text='唯一标识，如：pre_optimization_disc_application（同一服务类别内唯一）', max_length=100, verbose_name='文件类型代码')),
                ('name', models.CharField(help_text='显示名称，如：优化前刻盘申请', max_length=200, verbose_name='文件类型名称')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='禁用后不会在前端显示', verbose_name='是否启用')),
                ('description', models.TextField(blank=True, help_text='文件类型的详细说明', verbose_name='描述')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成果文件类型',
                'verbose_name_plural': '成果文件类型',
                'db_table': 'production_management_result_file_type',
                'ordering': ['service_category', 'order', 'id'],
                'indexes': [models.Index(fields=['service_category', 'is_active'], name='production__service_f0c5b9_idx'), models.Index(fields=['service_category', 'order'], name='production__service_e9f8b0_idx')],
                'unique_together': {('service_category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BusinessPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=100, verbose_name='回款阶段')),
                ('phase_description', models.TextField(blank=True, verbose_name='阶段描述')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划金额')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际金额')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('status', models.CharField(choices=[('pending', '待回款'), ('partial', '部分回款'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('trigger_condition', models.CharField(blank=True, max_length=100, verbose_name='触发条件')),
                ('condition_detail', models.CharField(blank=True, max_length=200, verbose_name='付款条件详情')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='contract_management.businesscontract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '商务回款计划',
                'verbose_name_plural': '商务回款计划',
                'db_table': 'business_payment_plan',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ComprehensiveAdjustmentCoefficient',
            fields=[
            ],
            options={
                'verbose_name': '综合调整系数',
                'verbose_name_plural': '综合调整系数',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contract_management.businesscontract',),
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('party_a', '甲方'), ('party_b', '乙方'), ('party_c', '丙方'), ('other', '其他')], default='party_a', max_length=20, verbose_name='单位类型')),
                ('party_name', models.CharField(max_length=200, verbose_name='单位名称')),
                ('credit_code', models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码')),
                ('legal_representative', models.CharField(blank=True, max_length=100, verbose_name='法定代表人')),
                ('project_manager', models.CharField(blank=True, max_length=100, verbose_name='项目负责人')),
                ('party_contact', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='办公地址')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='contract_management.businesscontract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '合同签约主体',
                'verbose_name_plural': '合同签约主体',
                'db_table': 'contract_party',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['contract', 'is_active'], name='contract_pa_contrac_c954c1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='businesscontract',
            index=models.Index(fields=['contract_number'], name='business_co_contrac_e8523a_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscontract',
            index=models.Index(fields=['status', 'contract_type'], name='business_co_status_a1c505_idx'),
        ),
        migrations.AddIndex(
            model_name='businesscontract',
            index=models.Index(fields=['contract_date'], name='business_co_contrac_dcd013_idx'),
        ),
    ]
