# Generated by Django 4.2.7 on 2025-11-21 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_center', '0018_add_project_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='initiation_document',
            field=models.FileField(blank=True, null=True, upload_to='project_initiation_documents/%Y/%m/', verbose_name='立项凭证文件'),
        ),
        migrations.AddField(
            model_name='project',
            name='initiation_document_type',
            field=models.CharField(blank=True, choices=[('winning_notice', '中标通知书'), ('business_commission', '业务委托书'), ('contract_text', '合同文本')], max_length=50, null=True, verbose_name='立项凭证类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='our_company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='我方单位名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('waiting_initiation_approval', '待立项审批'), ('initiation_rejected', '立项审批已驳回'), ('initiation_approved', '立项已审批'), ('waiting_receive', '待接收'), ('configuring', '配置中'), ('waiting_start', '待开工'), ('in_progress', '进行中'), ('suspended', '暂停'), ('completed', '已完工'), ('archived', '已归档'), ('cancelled', '已取消')], default='draft', max_length=30, verbose_name='项目状态'),
        ),
        migrations.CreateModel(
            name='ProjectInitiationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('submission_comment', models.TextField(blank=True, verbose_name='提交说明')),
                ('status', models.CharField(choices=[('pending_business_manager', '待商务经理提交'), ('pending_supervisor', '待直接上级审批'), ('pending_technical_manager', '待技术部经理审批'), ('approved', '审批通过'), ('rejected', '审批驳回')], default='pending_business_manager', max_length=30, verbose_name='审批状态')),
                ('supervisor_approved_time', models.DateTimeField(blank=True, null=True, verbose_name='直接上级审批时间')),
                ('supervisor_comment', models.TextField(blank=True, verbose_name='直接上级审批意见')),
                ('technical_manager_approved_time', models.DateTimeField(blank=True, null=True, verbose_name='技术部经理审批时间')),
                ('technical_manager_comment', models.TextField(blank=True, verbose_name='技术部经理审批意见')),
                ('approved_time', models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间')),
                ('rejected_time', models.DateTimeField(blank=True, null=True, verbose_name='驳回时间')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiation_approvals_approved', to=settings.AUTH_USER_MODEL, verbose_name='最终审批人')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initiation_approval', to='project_center.project', verbose_name='关联项目')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiation_approvals_rejected', to=settings.AUTH_USER_MODEL, verbose_name='驳回人')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiation_approvals_submitted', to=settings.AUTH_USER_MODEL, verbose_name='提交人（商务经理）')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiation_approvals_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='直接上级')),
                ('technical_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiation_approvals_technical', to=settings.AUTH_USER_MODEL, verbose_name='技术部经理')),
            ],
            options={
                'verbose_name': '项目立项审批',
                'verbose_name_plural': '项目立项审批',
                'db_table': 'project_center_initiation_approval',
                'ordering': ['-created_time'],
            },
        ),
    ]
